server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Cấu hình để hỗ trợ React Router (Single Page Application)
    # Nếu không tìm thấy file, sẽ trả về index.html thay vì lỗi 404
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Bỏ qua log cho các file tĩnh để giảm tải I/O
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }
}
